-- Migration script for Supabase
-- Run this in the Supabase SQL Editor

-- Create the users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all users to read (for this demo)
CREATE POLICY "Allow public read access" ON users
  FOR SELECT USING (true);

-- Create a policy that allows all users to insert (for this demo)
CREATE POLICY "Allow public insert access" ON users
  FOR INSERT WITH CHECK (true);

-- Create a policy that allows all users to update (for this demo)
CREATE POLICY "Allow public update access" ON users
  FOR UPDATE USING (true);

-- Create a policy that allows all users to delete (for this demo)
CREATE POLICY "Allow public delete access" ON users
  FOR DELETE USING (true);
